XGBoost:
  subsample: 0.9
  reg_lambda: 0.1
  reg_alpha: 0.1
  random_state: 100
  objective: "reg:squarederror"
  n_estimators: 200
  max_depth: 3
  learning_rate: 0.1
  gamma: 0.2
  colsample_bytree: 0.8